name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: thangapandi78/node-app:${{ github.sha }},thangapandi78/node-app:latest
      - name: Update gitops-repo
        run: |
          git clone https://x:${{ secrets.GITOPS_TOKEN }}@github.com/Thangam78/gitops-repo.git
          cd gitops-repo
          sed -i "s|image: thangapandi78/node-app:.*|image: thangapandi78/node-app:${{ github.sha }}|" deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main
